// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADfz-xYNzzILHd0Stg0a83o1aWhVl9E7Y',
    appId: '1:436035294230:web:4eaba5290aa66d20535137',
    messagingSenderId: '436035294230',
    projectId: 'flutter-firebase-app-73b8b',
    authDomain: 'flutter-firebase-app-73b8b.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-73b8b.firebasestorage.app',
    measurementId: 'G-61JPQZ88YF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfsU3N5t6H1q3qNDPGJDf55IBGoRC-qrg',
    appId: '1:436035294230:android:b2d6f2bdfec608d7535137',
    messagingSenderId: '436035294230',
    projectId: 'flutter-firebase-app-73b8b',
    storageBucket: 'flutter-firebase-app-73b8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnEMYiv4fyYuooY9LMOKsTuMfpzbmVzkQ',
    appId: '1:436035294230:ios:79ac8d8afbdbc2fc535137',
    messagingSenderId: '436035294230',
    projectId: 'flutter-firebase-app-73b8b',
    storageBucket: 'flutter-firebase-app-73b8b.firebasestorage.app',
    iosBundleId: 'com.sumina.hciproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnEMYiv4fyYuooY9LMOKsTuMfpzbmVzkQ',
    appId: '1:436035294230:ios:fcbed0f6fe18c6df535137',
    messagingSenderId: '436035294230',
    projectId: 'flutter-firebase-app-73b8b',
    storageBucket: 'flutter-firebase-app-73b8b.firebasestorage.app',
    iosBundleId: 'com.sumina.hciProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADfz-xYNzzILHd0Stg0a83o1aWhVl9E7Y',
    appId: '1:436035294230:web:3ea3a56ba132bdc3535137',
    messagingSenderId: '436035294230',
    projectId: 'flutter-firebase-app-73b8b',
    authDomain: 'flutter-firebase-app-73b8b.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-73b8b.firebasestorage.app',
    measurementId: 'G-27HM3CPC1E',
  );
}
